# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - id: postal-server-build
    dir: cli
    binary: postal_server
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/le0pard/postal_server/version.Version={{.Version}}
      - -X github.com/le0pard/postal_server/version.GitCommit={{.Commit}}
      - -X github.com/le0pard/postal_server/version.BuildTime={{.Date}}

archives:
  - id: postal-server-archive
    builds:
      - postal-server-build
    name_template: >-
      postal_server_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# snapshot:
#   name_template: "{{ .Tag }}"

# signs:
#   - artifacts: checksum
#     args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

sboms:
  - artifacts: archive

# changelog:
#   sort: asc
#   use: github
#   filters:
#     exclude:
#       - '^docs:'
#       - '^test:'

# brews:
#   -
#     name: certonid
#     ids:
#     - certonid-archive
#     goarm: "7"
#     # GitHub/GitLab repository to push the formula to
#     repository:
#       owner: certonid
#       name: homebrew-tap
#       branch: main
#       token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

#     commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
#     directory: Formula
#     homepage: "https://github.com/certonid/certonid"
#     description: "Serverless SSH Certificate Authority"
#     license: "MIT"
#     test: |
#       system "#{bin}/certonid", "--version"
#     install: |
#       bin.install "certonid"
